# network architecture
# encoder related
encoder: conformer
encoder_conf:
    output_size: 512    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.3
    positional_dropout_rate: 0.0
    attention_dropout_rate: 0.3
    input_layer: vgg2l # encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: true
    cnn_module_kernel: 15
    use_cnn_module: True
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'
    selfattention_layer_type: 'rel_selfattn'

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 3
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

decoder_lstm_conf:
    dtype: lstm
    dlayers: 1
    dunits: 512
    embed_dim: 1024
    dropout_rate_embed: 0.2
    dropout_rate: 0.1

joint_dim: 512

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.5
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

# use raw_wav or kaldi feature
raw_wav: false

# feature extraction
collate_conf:
    # waveform level config
    wav_distortion_conf:
        wav_dither: 0.0
        wav_distortion_rate: 0.0
        distortion_methods: []
    speed_perturb: false
    feature_extraction_conf:
        feature_type: 'fbank'
        mel_bins: 80
        frame_shift: 10
        frame_length: 25
        using_pitch: false
    # spec level config
    # spec_swap: false
    feature_dither: 0.0 # add dither [-feature_dither,feature_dither] on fbank feature
    spec_aug: true
    spec_aug_conf:
        warp_for_time: true
        num_t_mask: 5
        num_f_mask: 2
        max_t: 40
        max_f: 30
        max_w: 5


# dataset related
dataset_conf:
    max_length: 40960
    min_length: 0
    batch_type: 'static' # static or dynamic
    # the size of batch_size should be set according to your gpu memory size, here we used 2080ti gpu whose memory size is 11GB
    batch_size: 16
    sort: true

grad_clip: 5
accum_grad: 2
max_epoch: 100
log_interval: 100

optim: adam
optim_conf:
    lr: 0.0003
    weight_decay: 0.000001
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 15000
